### ISSUE TITLE
Choisir le français XOR l'anglais

### ISSUE THREAD

**Issue by gbip** [quentin-schiex/8PRO114-LAB1#1]
Bon les gars, il faut choisir !
Anglais XOR Français ? On peut pas avoir les deux dans le code.
Vu que 90% du code à l'air en français (tout sauf les test que j'ai écris, bizarre...) on peut passer les quelques trucs en anglais je suppose.

**Comment by quentin-schiex** [comment]
Je préfère suivre strictement l'interface du prof avec les noms de fonction en français. C'est à rendre demain. On peut encore bosser dessus demain si besoin.

**Comment by gbip** [comment]
Bah du coup il faut modifier un peu le code pour tout passer en français !

**Comment by gbip** [comment]
Vous avez utilisé clang-format ?

**Comment by quentin-schiex** [comment]
À rendre mardi pardon.
Et oui on a utilisé clang-format

**Comment by gbip** [comment]
Okay, je vais changer les mots anglais en mots français, je vous laisse faire des fonctions pour éviter les fonctions de plus de 20 lignes !

**Comment by quentin-schiex** [comment]
Enfin c'est pour le ”mardi 25 septembre" :o

**Comment by gbip** [comment]
Par contre je suis pas sur de très bien comprendre, mais il n'y a que les test, on ne peut pas jouer en ligne de commande ?

**Comment by quentin-schiex** [comment]
Effectivement. C'est pas demandé.

**Comment by gbip** [comment]
Okay ça roule !
